from DocumentCombiner import DocumentCombiner
from IndonesianPreprocessor import IndonesianPreprocessor
# from IndonesianPreprocessorWithNLP import IndonesianPreprocessorWithNLP
from SentenceIterator import SentenceIterator
from WordEmbeddingGenerator import WordEmbeddingGenerator
